### ISSUE TITLE
[Bug] Linker problems with specific lipids

### ISSUE THREAD

**Issue by tdrose** [SysMedOs/LipidLynxX#11] opened 2020-10-01 09:58 UTC
When using lipids in the linker/converter e.g. **PE(22:6_16:1)** the tool is able to convert them correctly into a notation which works with Swisslipids: Shorthand Notation: _PE 16:1_22:6_ ; LipidLynxX Notation: _PE(16:1_22:6)_ .

However, For some lipids this does not work correctly:

**Examples**:
1. Etherlipids: **PE(O-22:6_16:1)** should be converted into _PE(O-16:1_22:6)_ (Swisslipids ID: SLM:000069971), but does not work. So no Swisslipid DB entries are found.
2. Sphingolipids: **Cer(d14:0/26:0)** is wrongly converted into _Cer(14:0/26:0)_ , but the correct Swisslipids entry is _Ceramide (d14:0/26:0)_ (Swisslipids ID: SLM:000391713 )

**Comment by ZhixuNi** [comment] 2020-10-01 10:13
@tdrose  Thanks for the feedback!

This issue Cer(d14:0/26:0) is solved in the current dev version!
I will commit soon after I fix few other UI updates.
Please check the coming release of version 0.9.24 in the next few days.

The PE(O-22:6_16:1) issue is somehow a bit more complicated.
LipidLynxX currently will not change PE(O-22:6_16:1) to PE(O-16:1_22:6), since O-22:6 is a segment and _ indicate 16:0 is another FA.
Actually this is my first time to see PE(O-22:6_16:1)  style, since it is not the standard ShortHand notation style.
You can check this paper (PMID: 23549332):
[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3646453/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3646453/)
Please let me know if it possible how/where you get the style  PE(O-22:6_16:1) which probably means PE( O- (16:0_22:6) ).

Thanks!

### preview of Cer(d14:0/26:0) 
![2020-10-01 12 01 09 127 0 0 1 6e25595a1a00](https://user-images.githubusercontent.com/9975812/94796258-ce146c00-03de-11eb-9d6c-6d461bee9796.png)

**Comment by ZhixuNi** [comment] 2020-10-01 15:50
@tdrose Please check our latest release v0.9.24 from pull request  #12 to get version for Cer. Thanks!

**Comment by ZhixuNi** [comment] 2020-10-12 13:30
Hi @tdrose !

Have you tried our new version v0.9.24?
If the issue is solved and there are no further issues related to this topic this week, I will close this issue by the end of this week.

**Comment by ZhixuNi** [comment] 2020-10-19 11:21
Hi @tdrose !

I will close this issue for now. Feel free to add more comment if you want.

Best,

Zhixu Ni

**Closed by ZhixuNi** 2020-10-19 11:21 UTC
Labels: bug
